title: Ziv's Blog
tagline: Writing is thinking
description: This is the blog of Ziv. Most of the content will be notes on math, physics, programming, etc.
author:
  name: Ziv
  url: https://github.com/zivhacker
  twitter: zivhakka
url: "https://zivs.blog"
twitter:
  username: zivhakka
  card: summary
social:
  name: Ziv
  links:
    - https://twitter.com/zivhakka
    - https://github.com/zivhacker

defaults:
  - scope:
      path: ""      
      type: "posts"
    values:
      author: "Ziv"
  - scope:
      path: ""      
      type: "pages"
    values:
      author: "Ziv"

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

remote_theme: zivhacker/jekyll-theme-fermi

paginate: 20

google_analytics: G-2Y4WW65TCB

disqus: zivhakka

categories_path: /categories/
tags_path: /tags/

include:
  - _pages

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - script/
  - CNAME
  - README.md
